apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sarraf-db-secrets
  namespace: NAMESPACE_PLACEHOLDER
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/omerops-sarraf-dev/secrets/sarraf-db-password/versions/latest"
        fileName: "dbpassword.txt"
  
  # This block is the "Bridge" that creates the actual K8s Secret
  secretObjects:
  - secretName: sarraf-db-password-sync
    type: Opaque
    data:
    - objectName: "dbpassword.txt"
      key: password