apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sarraf-db-secrets
spec:
  # 'gcp' is the standard provider name for the GKE Managed Add-on
  provider: gcp 
  parameters:
    secrets: |
      - resourceName: "projects/omerops-sarraf-dev/secrets/sarraf-db-password/versions/latest"
        fileName: "db_password"
  
  # This block must NOT have a '|' pipe. It creates the native K8s secret.
  secretObjects:
  - secretName: sarraf-db-password-sync
    type: Opaque
    data:
    - objectName: "db_password" # Must match 'fileName' above
      key: "password"           # This is the key your Deployment 'env' looks for