apiVersion: v1
kind: ServiceAccount
metadata:
  name: sarraf-backend-ksa
  namespace: default
  annotations:
    # This connects the KSA to the GSA created by Terraform
    iam.gke.io/gcp-service-account: sarraf-backend-gsa@omerops-sarraf-dev.iam.gserviceaccount.com