apiVersion: v1
kind: Service
metadata:
  name: sarraf-backend-service
  labels:
    app: sarraf-backend
spec:
  selector:
    app: sarraf-backend
  ports:
    - protocol: TCP
      port: 80.  # The port the Load Balancer listens on
      targetPort: 8080 # The port your Go app is listening on
  type: LoadBalancer # This tells Google to give you a Public IP