apiVersion: v1
kind: Service
metadata:
  name: sarraf-backend-service
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: sarraf-backend
  annotations:
    # Use Premium network tier for lower latency in the Gulf region
    cloud.google.com/network-tier: Premium
spec:
  selector:
    app: sarraf-backend
  ports:
    - protocol: TCP
      port: 80           # External port (Load Balancer)
      targetPort: 8080   # Internal port (Your FastAPI/Go app)
  type: LoadBalancer