apiVersion: v1
kind: ServiceAccount
metadata:
  name: sarraf-backend-ksa
  namespace: NAMESPACE_PLACEHOLDER
  annotations:
    iam.gke.io/gcp-service-account: sarraf-backend-gsa@omerops-sarraf-dev.iam.gserviceaccount.com
