apiVersion: v1
kind: Service
metadata:
  name: sarraf-backend-service
  labels:
    app: sarraf-backend
spec:
  selector:
    app: sarraf-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
