apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sarraf-prod

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/monitoring
  - namespace.yaml
  - networking.yaml

patches:
  # Backend: GKE-specific service account annotation
  - target:
      kind: ServiceAccount
      name: sarraf-backend-ksa
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: sarraf-backend-gsa@omerops-sarraf-prod.iam.gserviceaccount.com

  # Backend: Set DB_USER and Cloud SQL connection name
  - target:
      kind: Deployment
      name: sarraf-backend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: sarraf-backend-gsa@omerops-sarraf-prod.iam
      - op: replace
        path: /spec/template/spec/containers/1/args/3
        value: omerops-sarraf-prod:me-central1:sarraf-db-prod

images:
  - name: sarraf-api
    newName: me-central1-docker.pkg.dev/omerops-sarraf-prod/sarraf-docker-repo/sarraf-api
    newTag: "a8aa40b0d362e0d8c309633a8ba8a59525b20156"
  - name: sarraf-frontend
    newName: me-central1-docker.pkg.dev/omerops-sarraf-prod/sarraf-docker-repo/sarraf-frontend
    newTag: "a8aa40b0d362e0d8c309633a8ba8a59525b20156"
