apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: sarraf-dev
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.0.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "sarraf-admin"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: sarraf-dashboard
          mountPath: /var/lib/grafana/dashboards/sarraf
        - name: pods-dashboard
          mountPath: /var/lib/grafana/dashboards/pods
        - name: finops-dashboard
          mountPath: /var/lib/grafana/dashboards/finops
        - name: perpod-dashboard
          mountPath: /var/lib/grafana/dashboards/perpod
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider
      - name: sarraf-dashboard
        configMap:
          name: sarraf-dashboard
      - name: pods-dashboard
        configMap:
          name: sarraf-pods-dashboard
      - name: finops-dashboard
        configMap:
          name: sarraf-finops-dashboard
      - name: perpod-dashboard
        configMap:
          name: sarraf-perpod-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: sarraf-dev
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: sarraf-dev
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service.sarraf-dev.svc:9090
      isDefault: true
