apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sarraf-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omermd529/sarraf-fintech-interchange.git
    targetRevision: production
    path: gitops/overlays/gke-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sarraf-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
